# This is a basic workflow to help you get started with Actions

name: Push to Glitch

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out the Required Branch
      uses: actions/checkout@v2

    # Synchronize the Branch with the Glitch Repository
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/bodo-hugo-barwich/plack-pwa-api.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: ${{ secrets.GLITCH_GIT_URL }}
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
